name: a2b_hme
channels:
  - defaults
  - conda-forge
dependencies:
  - ezc3d=1.5.10
  - numpy=1.23.5
  - pip=24.0
  - python=3.11
  - scikit-learn==1.3.2
  - tensorboard=2.17.0
  - einops=0.8.0
  - pip:
    - torch==2.3.1
    - opencv-python==4.10.0.84
    - smplx[all]==0.1.28
    - h5py==3.11.0
    - git+https://github.com/anibali/posekit.git@c9d61d5fa84b3e87dd1a7f0e99ae58aa1e4c759d#egg=posekit
    - git+https://github.com/anibali/aspset-510.git
    - human_body_prior==0.8.5.0
    - omegaconf==2.3.0
    - loguru==0.7.2