name: a2b_hme
channels:
  - defaults
  - conda-forge
dependencies:
  - pip=25.0
  - python=3.13
  - pip:
    - torch==2.6.0
    - opencv-python==4.11.0.86
    - smplx[all]==0.1.28
    - h5py==3.12.1
    - git+https://github.com/anibali/posekit.git@c9d61d5fa84b3e87dd1a7f0e99ae58aa1e4c759d#egg=posekit
    - git+https://github.com/anibali/aspset-510.git
    - human_body_prior==0.8.5.0
    - omegaconf==2.3.0
    - loguru==0.7.3
    - k3d==2.16.1
    - class_registry==2.1.2
    - scikit-learn==1.6.1
    - tensorboard==2.18.0
    - einops==0.8.1
    - ezc3d==1.5.18
    - numpy==2.2.2